### ISSUE TITLE
Implement paginations

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-web#166]
The following sections need properly paginating:

- [ ] - Society productions
- [X] - User bookings
- [ ] Lots of places with performances (production book index page, production index page, etc)

Also, some paginated tables, especially in admin panel, don't show loading spinners (either initial load or subsequent updates)

**Comment by Guidedriver0** [comment]
? @atoff

**Comment by atoff** [comment]
idk tbh, need to do an audit and check

**Comment by zst-c** [comment]
Focus on #377
