### ISSUE TITLE
Production page: Handle no performances

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-web#197]
When a production has no (visible) performances, we should show a nice message saying that there are no performances available at the moment

**Comment by streth11** [comment]
@atoff If the prodution has no performacnes it is impossible to navigate to the production page unless the slug is known and entered into the URL.
I thought we established that we wouldnt

**Comment by atoff** [comment]
This may still be an issue in an edge case, so we should still do this. It's an easy thing to implement, so no reason not to
