### ISSUE TITLE
Box office page is hard to use on mobile

### ISSUE THREAD

**Issue by aeroniemi** [BristolSTA/uobtheatre-web#222]
used the phone box office page during mtb to speed up ticketing - the check in all tickets button was kinda hard to click, and we clicked it unintentionally a few times - needs a bit of looking at!

**Comment by streth11** [comment]
Seconded

Hard to scroll over and press them

![image](https://user-images.githubusercontent.com/61627133/144721715-eb32e570-280d-40ce-9740-b050a434cba2.png)
