### ISSUE TITLE
Performance Admin Society Income Incorrect

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-web#286]
On performance admin pages, the figure given for Performance Net Society Revenue is using the wrong value. It needs to display the society transfer value for that performance, where as it currently shows the net income (i.e. including squares cut and our cut)

**Comment by streth11** [comment]
This is an API issue, awaiting api transfer-bookings

https://github.com/BristolSTA/uobtheatre-web/blob/23f962f102069cf1a4490cd9eda10a3ef54a6fa3/pages/administration/productions/_productionSlug/index.vue#L52-L60

**Comment by atoff** [comment]
> This is an API issue i presume, as this is directly from the schema
> 
> https://github.com/BristolSTA/uobtheatre-web/blob/23f962f102069cf1a4490cd9eda10a3ef54a6fa3/pages/administration/productions/_productionSlug/index.vue#L52-L60

This is a problem with performances, not productions: https://github.com/BristolSTA/uobtheatre-web/blob/23f962f102069cf1a4490cd9eda10a3ef54a6fa3/pages/administration/productions/_productionSlug/performances/_performanceId/index.vue#L107
