### ISSUE TITLE
Implement Checked In At / Checked In By

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-web#294]
Implement the new Checked In At (timestamp) and Checked In By (user) in appropriate admin areas to assist with ticket checking.
Probably in box office (e.g. when a ticket is scanned but already checked in), box office booking detail page and maybe admin page for booking too?

**Comment by atoff** [comment]
Done in new box office UI, but should be added to admin booking inspection too

**Comment by HappyNTH** [comment]
See https://github.com/BristolSTA/uobtheatre-web/pull/346
