### ISSUE TITLE
Find cause of "Authentication Error" when checking in tickets

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-web#303]
Lots of cases of people, logged in, scanning tickets and a "Authentication" sweet alert popping up.

Seems to happen when people are using phones logged into the same account to scan.
Also sometimes on the PWA when a refresh hasn't been had for a while (maybe a caching problem? might be sovled by Nuxt3 update)

**Comment by Guidedriver0** [comment]
Has this been resolved @atoff

**Comment by atoff** [comment]
> Has this been resolved @atoff

Unless you have seen it recently on shows with the new box office I think probably yes? However I think we potentially still had issues when someone was logged in on multiple devices?

**Comment by HappyNTH** [comment]
Closed unless the issue crops up again
