### ISSUE TITLE
Upcoming productions can show old productions

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-web#69]
At the moment the upcoming production query uses:
`productions(first: 9, orderBy: "start", after: $afterCursor)`

If the real API returns old productions to this query method, then we can get old productions. Either need to sort our end by modifying the query, or see how james plans to handle this.

This will affect the homepage and the `/productions` page

**Comment by streth11** [comment]
surely this is not a huge issue for the `/productions` page, as if both of those pages it would look very empty if nothing is happening;
or at least on `/productions` we should have a section for old productions
